train_dataset:
  coco:
    is_train: true
    datadir: /localdisk/coco
    download: false
    shuffle: false
    drop_last: false
val_dataset:
  coco:
    is_train: false
    datadir: /localdisk/coco
    download: false
    shuffle: false
    drop_last: false
optimizer:
  sgd:
    lr: 2.5e-3
    weight_decay: 5e-4
    momentum: 0.9
model:
  ssd:
    input_size: 300
    overlap_threshold: 0.5
    nms_max_detections: 200
    pretrained_backbone: /mnt/r1z1/laura/composer/resnet34-333f7ec4.pth
    initializers: {}
loggers:
  - tqdm: {}
train_batch_size: 128
eval_batch_size: 32
seed: 0
validate_every_n_epochs: 1
grad_accum: 1
device:
  gpu: {}
max_duration: 70ep
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
precision: amp
