train_dataset:
  glue:
    task: stsb
    tokenizer_name: bert-base-uncased
    split: train
    max_seq_length: 256
    shuffle: false
    drop_last: false
evaluators:
  - label: glue_stsb
    eval_dataset:
      glue:
        task: stsb
        tokenizer_name: bert-base-uncased
        split: validation
        max_seq_length: 256
        shuffle: false
        drop_last: false
    metric_names:
      - SpearmanCorrCoef
model:
  bert_classification:
    num_labels: 1
    use_pretrained: true
    pretrained_model_name: bert-base-uncased
optimizers:
  decoupled_adamw:
    lr: 3.0e-5
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 3.0e-6
schedulers:
  - linear_decay_with_warmup:
      t_warmup: 0.06dur
max_duration: 10ep
train_batch_size: 32
eval_batch_size: 32
seed: 19
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 8
  timeout: 0
  prefetch_factor: 2
grad_accum: 1
eval_interval: 200ba
callbacks:
  - lr_monitor: {}
load_path: https://storage.googleapis.com/llm_checkpoints/bert_checkpoint/bert_checkpoints/ep7.pt
load_weights_only: true
load_strict_model_weights: false
precision: fp32 # Eval requires FP32
