yaml-files:
- "*.yaml"
- "*.yml"
- .yamllint

ignore: |
  wandb
  *

rules:
  braces:
    forbid: non-empty
  brackets:
    forbid: false
  colons: enable
  commas: enable
  comments: enable
  comments-indentation: enable
  document-end:
    present: false
  document-start:
    present: false
  empty-lines: enable
  empty-values: disable
  hyphens: enable
  indentation:
    spaces: 2
    indent-sequences: false
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  line-length:
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: enable
  new-lines: enable
  octal-values: enable
  quoted-strings:
    quote-type: double
    required: false
  trailing-spaces: enable
  truthy: disable
