# Build configuration for anaconda

package:
  name: mosaicml
  version: "0.3.1"

source:
  git_url: https://github.com/mosaicml/composer.git
  # TODO change to "v0.4.0"
  git_rev: "dev"
  git_depth: 1

build:
  number: 0
  noarch: python
  entry_points:
    - composer = composer.cli.launcher:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.7
  run:
    - python >=3.7
    - pyyaml >=5.4.1
    - pytorch >=1.9
    - torch-optimizer ==0.1.0
    - torchmetrics >=0.6.0
    - torchvision >=0.9.0
    - tqdm >=4.62.3
    - yahp >=0.0.14
    - requests >=2.26.0
    - numpy ==1.21.5
    - apache-libcloud >=3.3.1
    - psutil >=5.8.0
  run_constrained:
    - wandb >=0.12.2
    - monai >=0.7.0
    - scikit-learn >=1.0.1
    - timm >=0.5.4
    - transformers >=4.11.3
    - datasets >=1.14.0

test:
  requires:
    - fasteners >=0.16.3
    - pytest >=7.0.0
    - toml >=0.10.2
    - ipython >=7.29.0
    - ipykernel >=6.5.0
    - jupyter >=1.0.0
    - pytest-timeout >=1.4.2
    - testbook >=0.4.2
    # Including all run_constrained requirements in the test requirements, so those tests will not be import-skipped
    - pip  # for deepspeed, since deepspeed is not available on anaconda
    - wandb >=0.12.2
    - monai >=0.7.0
    - scikit-learn >=1.0.1
    - timm >=0.5.4
    - transformers >=4.11.3
    - datasets >=1.14.0
  files:
    - "**/composer/**"
    - "**/tests/**"
    - "**/notebooks/**"
    - "**/examples/**"
    - "**/pyproject.toml"
  imports:
    - composer
    - tests
  commands:
    - pip install deepspeed>=0.5.5  # deepspeed is not available on conda
    - pytest --duration all -m "not notebooks and not gpu"
    - python -m composer.cli.launcher -n 2 -m pytest --duration all -m "not notebooks and not gpu"

about:
  home: https://www.mosaicml.com
  license: Apache 2.0
  license_file: LICENSE
  summary: "composing methods for ML training efficiency"
  dev_url: https://github.com/mosaicml/composer
  doc_url: https://docs.mosaicml.com
