# Build configuration for anaconda

package:
  name: mosaicml
  version: "{{ load_setup_py_data().get('version') }}"

source:
  git_url: ./

build:
  number: 0
  noarch: python
  entry_points:
    - composer = composer.cli.launcher:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3.7
    - setuptools
    - git
  run:
    - python >=3.7,<4
    - pyyaml >=6.0,<7
    - pytorch >=1.10,<2
    - torch-optimizer >=0.1.0,<0.2
    - torchmetrics >=0.7.0,<0.8
    - torchvision >=0.9.0 # torchvision has strict pytorch requirements
    - tqdm >=4.62.3,<5
    - yahp ==0.1.1
    - requests >=2.26.0,<3
    - numpy >=1.21.5,<1.23.0
    - psutil >=5.8.0,<6
    - coolname >=1.1.0,<2
    - py-cpuinfo>=8.0.0,<9
    - packaging >=21.3.0,<22
    - importlib-metadata >=4.11.0,<5
  run_constrained:
    - wandb >=0.12.17,<0.13
    - monai >=0.8.0,<0.9
    - scikit-learn >=1.0.1,<2
    # - timm >=0.5.4 # This timm version is not available on conda
    - transformers >=4.11,<5
    - datasets >=1.14,<2
    - pycocotools >=2.0.4,<3
    - boto3 >=1.21.45,<2
    - apache-libcloud >=3.5.1,<4
    - paramiko>=2.11.0,<3
    - tensorboard>=2.9.1,<3.0.0

test:
  requires:
    - fasteners ==0.17.3,<0.18
    - pytest >=7.1.0,<8
    - toml >=0.10.2,<0.11
    - ipython >=8.4.0,<9
    - ipykernel ==6.13.1,<7
    - jupyter >=1.0.0,<2
    - testbook >=0.4.2,<0.5
    # Including all run_constrained requirements in the test requirements, so those tests will not be import-skipped
    - pip # Required for dependencies not available on conda
    - wandb >=0.12.17,<0.13
    - monai >=0.8.0,<0.9
    - scikit-learn >=1.0.1,<2
    - transformers >=4.11,<5
    - datasets >=1.14,<2
    - pycocotools >=2.0.4,<3
    - boto3 >=1.21.45,<2
    - apache-libcloud>=3.5.1,<4
    - paramiko>=2.11.0,<3
    - cpuonly >=2.0,<3
    - moto >=3.1.12,<3.2
    - cryptography >=37.0.2,<38
    - tensorboard>=2.9.1,<3.0.0
    - pytest-httpserver>=1.0.4,<1.1
  files:
    - "**/composer/**"
    - "**/tests/**"
    - "**/examples/**"
    - "**/pyproject.toml"
    - "**/Makefile"
  imports:
    - composer
    - tests
  commands:
    # deepspeed, codeblocks, and mock-ssh-server are not available on conda, and timm has a conda version conflict
    - pip install 'deepspeed>=0.5.5' 'timm>=0.5.4' 'pytest_codeblocks==0.16.1' 'mock-ssh-server>=0.9.1,<1'
    - make test EXTRA_ARGS="-v -m 'not gpu and not vision and not daily and not remote'"
    - make test-dist WORLD_SIZE=2 EXTRA_ARGS="-v -m 'not gpu and not vision and not daily and not remote'"

about:
  home: https://www.mosaicml.com
  license: Apache 2.0
  license_file: LICENSE
  summary: "composing methods for ML training efficiency"
  dev_url: https://github.com/mosaicml/composer
  doc_url: https://docs.mosaicml.com
