run_name: mcli-test-hello-world
platform: r1z1
gpu_type: a100_80gb
gpu_num: 8
image: mosaicml/pytorch
integrations:
  - integration_type: git_repo
    git_repo: mosaicml/composer
    git_branch: dev
    pip_install: --user -e .[all]
command: |
  composer_collect_env
