train_dataset:
  lm:
    split: train
    datadir:
      - /datasets/wikipedia_saved_bert_128
      - /datasets/bookcorpus_saved_bert_128
    tokenizer_name: bert-base-uncased
    seed: 19
    shuffle: true
    drop_last: false
    subsample_ratio: 1.0
    use_masked_lm: true
    mlm_probability: 0.15
    train_sequence_length: 128
    val_sequence_length: 128
val_dataset:
  lm:
    split: validation
    datadir:
      - /datasets/wikipedia_saved_bert_128
      - /datasets/bookcorpus_saved_bert_128
    tokenizer_name: bert-base-uncased
    seed: 19
    shuffle: true
    drop_last: false
    subsample_ratio: 0.02
    use_masked_lm: true
    mlm_probability: 0.15
    train_sequence_length: 128
    val_sequence_length: 128
model:
  bert:
    use_pretrained: false
    tokenizer_name: bert-base-uncased
    pretrained_model_name: bert-base-uncased
optimizer:
  decoupled_adamw:
    lr: 5.0e-4
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 1.0e-5
schedulers:
  - linear_decay_with_warmup:
      warmup_time: 0.06dur
loggers:
  - tqdm: {}
max_duration: 7ep # Baseline is 256M samples, 7 epochs is ~280M samples
train_batch_size: 4000
eval_batch_size: 2000
seed: 19
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 8
  timeout: 0
  prefetch_factor: 2
grad_accum: 2
precision: amp
grad_clip_norm: None
validate_every_n_batches: 1000
validate_every_n_epochs: 1
