train_dataset:
  mnist:
    is_train: true
    datadir: /datasets/mnist
    download: true
    shuffle: true
    drop_last: true
val_dataset:
  mnist:
    is_train: false
    datadir: /datasets/mnist
    download: true
    shuffle: false
    drop_last: false
optimizers:
  sgd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 1.0e-4
schedulers:
  - cosine_decay: {}
model:
  mnist_classifier:
    initializers:
      - kaiming_normal
      - bn_uniform
    num_classes: 10
max_duration: 10ep
train_batch_size: 2048
eval_batch_size: 1000
seed: 17
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
