train_dataset:
  ade20k:
    datadir: null
    split: train
    base_size: 512
    final_size: 512
    drop_last: true
    shuffle: true
val_dataset:
  ade20k:
    datadir: null
    split: val
    base_size: 512
    final_size: 512
    drop_last: false
    shuffle: false
optimizer:
  decoupled_sgdw:
    lr: 0.04
    momentum: 0.9
    weight_decay: 5.0e-5
    dampening: 0
    nesterov: false
schedulers:
  cosine_decay:
    T_max: "127ep"
    eta_min: 0
    verbose: false
    interval: step
model:
  deeplabv3:
    initializers:
      - kaiming_normal
      - bn_uniform
    num_classes: 150
    backbone_arch: resnet101
    is_backbone_pretrained: true
    sync_bn: true
loggers:
  - tqdm: {}
max_epochs: 127
train_batch_size: 128
eval_batch_size: 32
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
validate_every_n_epochs: 1
grad_accum: 4
precision: amp
ddp_timeout: 60
