train_dataset:
  ade20k:
    datadir: null
    split: train
    base_size: 512
    final_size: 512
    drop_last: true
    shuffle: true
val_dataset:
  ade20k:
    datadir: null
    split: val
    base_size: 512
    final_size: 512
    drop_last: false
    shuffle: false
optimizers:
  sgd:
    lr: 0.01
    momentum: 0.9
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: false
schedulers:
  - polynomial:
      alpha_f: 0.01
      power: 0.9
model:
  deeplabv3:
    initializers:
      - kaiming_normal
      - bn_ones
    num_classes: 150
    backbone_arch: resnet101
    backbone_weights: IMAGENET1K_V1
    use_plus: true
    sync_bn: true
max_duration: 127ep
train_batch_size: 16
eval_batch_size: 16
seed: 17
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
dist_timeout: 60
