train_dataset:
  ade20k:
    datadir: null
    split: train
    base_size: 512
    final_size: 512
    drop_last: true
    shuffle: true
val_dataset:
  ade20k:
    datadir: null
    split: val
    base_size: 512
    final_size: 512
    drop_last: false
    shuffle: false
optimizers:
  decoupled_sgdw:
    lr: 0.08
    momentum: 0.9
    weight_decay: 5.0e-5
    dampening: 0
    nesterov: false
schedulers:
  - cosine_decay:
      t_max: 1dur
model:
  deeplabv3:
    initializers:
      - kaiming_normal
      - bn_ones
    num_classes: 150
    backbone_arch: resnet101
    backbone_weights: IMAGENET1K_V2
    use_plus: true
    sync_bn: false
max_duration: 128ep
train_batch_size: 128
eval_batch_size: 128
seed: 17
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
dist_timeout: 60
