train_dataset:
  imagenet:
    resize_size: -1
    crop_size: 224
    is_train: true
    datadir: /datasets/ImageNet
    shuffle: true
    drop_last: true
val_dataset:
  imagenet:
    resize_size: 256
    crop_size: 224
    is_train: false
    datadir: /datasets/ImageNet
    shuffle: False
    drop_last: False
optimizers:
  rmsprop:
    lr: 0.08
    momentum: 0.9
    alpha: 0.9
    eps: 0.01
    weight_decay: 1.0e-5
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: "16ep"
model:
  efficientnetb0:
    drop_connect_rate: 0.2
    num_classes: 1000
max_duration: 400ep
train_batch_size: 4096
eval_batch_size: 2048
seed: 17
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
