# INFO:__main__:Predicted loss: 3.2042232768969785
# INFO:__main__:Predicted perplexity: 24.63635695536824
train_dataset:
  lm:
    split: train
    datadir: /datasets/openwebtext_saved
    tokenizer_name: gpt2
    seed: 17
    shuffle: false
    drop_last: false
    num_tokens: 7340032000 # 14000 (batches) * 512 (batch_size) * 1024 (seq_len)
    use_masked_lm: false
val_dataset:
  lm:
    split: validation
    datadir: /datasets/openwebtext_saved
    tokenizer_name: gpt2
    seed: 17
    shuffle: false
    drop_last: false
    num_tokens: 102400000 # 100000 (seq) * 1024 (seq_len)
    use_masked_lm: false
model:
  gpt2:
    use_pretrained: false
    tokenizer_name: gpt2
    model_config:
      activation_function: gelu_new
      architectures:
        - GPT2LMHeadModel
      attn_pdrop: 0.1
      bos_token_id: 50256
      embd_pdrop: 0.1
      eos_token_id: 50256
      initializer_range: 0.02
      layer_norm_epsilon: 1.0e-05
      model_type: gpt2
      n_ctx: 1024
      n_embd: 768
      n_head: 12
      n_inner: 3072
      n_layer: 12
      n_positions: 1024
      resid_pdrop: 0.1
      scale_attn_weights: true
      summary_activation: null
      summary_first_dropout: 0.1
      summary_proj_to_labels: true
      summary_type: cls_index
      summary_use_proj: true
      task_specific_params:
        text-generation:
          do_sample: true
          max_length: 50
      transformers_version: 4.11.0.dev0
      use_cache: true
      vocab_size: 50257
optimizer:
  adamw:
    lr: 6.0e-4
    betas:
      - 0.9
      - 0.999
    eps: 1.0e-08
    weight_decay: 0.0
schedulers:
  - cosine_decay_with_warmup:
      warmup_time: 140ba
loggers:
  - tqdm: {}
max_duration: 1ep
train_batch_size: 512
eval_batch_size: 8 # use micro_bs_per_gpu = 1 to accomodate 10GB limit
seed: 17
device:
  gpu: {}
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 8
  timeout: 0
  prefetch_factor: 2
precision: amp
grad_clip_norm: 1.0
grad_accum: 22
validate_every_n_batches: 1000
validate_every_n_epochs: 1
