train_dataset:
  streaming_imagenet1k:
    remote: your-bucket-here
    local: /tmp/mds-cache/mds-imagenet1k/
    split: train
    resize_size: -1
    crop_size: 224
    shuffle: true
    drop_last: true
val_dataset:
  streaming_imagenet1k:
    remote: your-bucket-here
    local: /tmp/mds-cache/mds-imagenet1k/
    split: val
    resize_size: 256
    crop_size: 224
    shuffle: false
    drop_last: false
optimizers:
  decoupled_sgdw:
    lr: 2.048
    momentum: 0.875
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: false
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: "8ep"
model:
  resnet:
    model_name: resnet50
    initializers:
      - kaiming_normal
      - bn_uniform
    num_classes: 1000
max_duration: 90ep
train_batch_size: 2048
eval_batch_size: 2048
seed: 17
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
