train_dataset:
  streaming_cifar10:
    remote: your-bucket-here
    local: /tmp/mds-cache/mds-cifar10/
    split: train
    shuffle: true
    drop_last: true
val_dataset:
  streaming_cifar10:
    remote: your-bucket-here
    local: /tmp/mds-cache/mds-cifar10/
    split: val
    shuffle: false
    drop_last: false
optimizers:
  decoupled_sgdw:
    lr: 1.2
    momentum: 0.9
    weight_decay: 2.0e-3
schedulers:
  - multistep_with_warmup:
      t_warmup: "5ep"
      milestones:
        - "80ep"
        - "120ep"
      gamma: 0.1
model:
  resnet_cifar:
    model_name: resnet_56
    initializers:
      - kaiming_normal
      - bn_uniform
max_duration: 160ep
train_batch_size: 1024
eval_batch_size: 1000
seed: 17
grad_accum: 1
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
