train_dataset:
  imagenet:
    resize_size: -1
    crop_size: 224
    is_train: true
    use_synthetic: true
    shuffle: true
    drop_last: true
val_dataset:
  imagenet:
    resize_size: 256
    crop_size: 224
    is_train: false
    use_synthetic: true
    shuffle: true
    drop_last: true
optimizers:
  decoupled_sgdw:
    lr: 2.048
    momentum: 0.875
    weight_decay: 5.0e-4
    dampening: 0
    nesterov: false
schedulers:
  - cosine_decay_with_warmup:
      t_warmup: "8ep"
model:
  resnet:
    model_name: resnet18
    initializers:
      - kaiming_normal
      - bn_uniform
    num_classes: 1000
max_duration: 90ep
train_batch_size: 2048
eval_batch_size: 1000
train_subset_num_batches: 10
eval_subset_num_batches: 10
seed: 17
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
grad_accum: 1
