train_dataset:
  brats:
    is_train: true
    datadir: /datasets/01_2d
    download: false
    shuffle: true
    drop_last: true
val_dataset:
  brats:
    is_train: false
    datadir: /datasets/01_2d
    download: false
    shuffle: false
    drop_last: false
optimizer:
  radam:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0.0001
schedulers:
  - constant:
      interval: step
model:
  unet:
    initializers:
      - kaiming_normal
      - bn_ones
loggers:
  - tqdm: {}
max_epochs: 200
total_batch_size: 64
eval_batch_size: 8
seed: 0
validate_every_n_epochs: 1
grad_accum: 1
device:
  gpu: {}
dataloader:
  pin_memory: true
  timeout: 0
  prefetch_factor: 2
  persistent_workers: true
  num_workers: 8
precision: amp
