name: YAPF
description: Format with YAPF
inputs:
  working_directory:
    required: true
    description: Root of the repo. Should be set to GITHUB_WORKSPACE
  args:
    description: YAPF args
    default: "-drp ."
    required: false
runs:
  using: composite
  steps:
    - name: Install YAPF
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -ex
        pip install yapf
    - name: Run YAPF
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        YAPF_ARGS: ${{ inputs.args }}
      run: |
        set -ex
        yapf ${YAPF_ARGS}
