name: ISort
description: Sort imports
inputs:
  working_directory:
    required: true
    description: Root of the repo. Should be set to GITHUB_WORKSPACE
  args:
    description: ISort args
    default: ". -c -v"
    required: false
runs:
  using: composite
  steps:
    - name: Install ISort
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -ex
        pip install isort
    - name: Run ISort
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        ISORT_ARGS: ${{ inputs.args }}
      run: |
        set -ex
        isort ${ISORT_ARGS}
