algorithms:
  - blurpool:
      blur_first: true
      min_channels: 16
      replace_convs: true
      replace_maxpools: true
  - channels_last: {}
  - colout:
      batch: true
      p_col: 0.05
      p_row: 0.05
      resize_target: auto
  - ema:
      half_life: 100ba
      update_interval: 20ba
  - label_smoothing:
      smoothing: 0.13
  - mixup:
      alpha: 0.25
      interpolate_loss: false
  - progressive_resizing:
      delay_fraction: 0.2
      finetune_fraction: 0.2
      initial_scale: 0.6
      mode: resize
      resize_targets: false
      size_increment: 4
  - randaugment:
      augmentation_set: all
      depth: 1
      severity: 10
  - sam:
      epsilon: 1.0e-12
      interval: 5
      rho: 0.5
  - stochastic_depth:
      drop_distribution: linear
      drop_rate: 0.1
      drop_warmup: 0.0dur
      stochastic_method: sample
      target_layer_name: ResNetBottleneck
callbacks:
  - lr_monitor: {}
  - speed_monitor:
      window_size: 100
dataloader:
  num_workers: 8
  persistent_workers: true
  pin_memory: true
  prefetch_factor: 2
  timeout: 0.0
device:
  gpu: {}
eval_batch_size: 2048
loggers:
  - progress_bar:
      stream: stderr
model:
  resnet:
    groups: 1
    initializers:
      - KAIMING_NORMAL
      - BN_UNIFORM
      - LINEAR_LOG_CONSTANT_BIAS
    loss_name: binary_cross_entropy_with_logits
    model_name: resnet50
    num_classes: 1000
    pretrained: false
    width_per_group: 64
optimizers:
  decoupled_sgdw:
    dampening: 0.0
    lr: 2.048
    momentum: 0.875
    nesterov: false
    weight_decay: 0.0003
precision: AMP
max_duration: 90ep
scale_schedule_ratio: 3 # Fraction of 90 epochs to train for. >2.6 for spicy recipe
schedulers:
  cosine_decay_with_warmup:
    alpha_f: 0.0
    t_max: 1dur
    t_warmup: 8ep
seed: 42
train_batch_size: 2048
train_dataset:
  imagenet:
    crop_size: 176
    datadir: /path/to/imagenet # /path/to/imagenet
    drop_last: true
    is_train: true
train_subset_num_batches: -1
val_dataset:
  imagenet:
    crop_size: 224
    datadir: /path/to/imagenet # /path/to/imagenet
    drop_last: false
    is_train: false
    resize_size: 232
    shuffle: false
