name: Composer Pip Install
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  ComposerPip:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
        install_version:
          - ""
          - "[all]"
          - "[dev]"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Setup
        run: |
          set -exuo pipefail
          python -m pip install --upgrade pip wheel
          python -m pip install -e .${{ matrix.install_version }}
      - name: Run import
        id: tests
        run: |
          set -exuo pipefail
          python -c "import composer"
