name: Pytest-CPU
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  pytest:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python_version: "3.8"
            container:  mosaicml/pytorch:1.11.0_cpu-python3.8-ubuntu20.04
          - python_version: "3.9"
            container:  mosaicml/pytorch:1.12.1_cpu-python3.9-ubuntu20.04 
          - python_version: "3.9"
            container:  mosaicml/pytorch_vision:1.12.1_cpu-python3.9-ubuntu20.04
          - python_version: "3.10"
            container:  mosaicml/pytorch:1.13.0_cpu-python3.10-ubuntu20.04
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python_version }}
      - name: Setup
        run: |
          set -ex
          python -m pip install --upgrade pip wheel
          python -m pip install -e .[all]
      - name: Run Tests
        id: tests
        run: |
          set -ex
          python3 -m pytest
