name: Pytest-CPU
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  pytest:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python_version: "3.8"
            container:  mosaicml/pytorch:1.11.0_cpu-python3.8-ubuntu20.04
          - python_version: "3.9"
            container:  mosaicml/pytorch:1.12.1_cpu-python3.9-ubuntu20.04
          - python_version: "3.9"
            container:  mosaicml/pytorch_vision:1.12.1_cpu-python3.9-ubuntu20.04
          - python_version: "3.10"
            container:  mosaicml/pytorch:1.13.0_cpu-python3.10-ubuntu20.04
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ matrix.python_version }}
      - name: Setup python
        run: |
          set -ex
          export PATH=/composer-python:$PATH
      - name: printenv
        run: |
          printenv
      - name: Setup
        run: |
          set -ex
          python -m pip install --upgrade pip wheel
          python -m pip install -e .[all]
      - name: Run Tests
        id: tests
        run: |
          set -ex
          export WANDB_ENTITY='mosaicml-public-integration-tests'
          export WANDB_PROJECT="integration-tests-${BUILD_NUMBER}-$(date +%s)"
          export S3_BUCKET='mosaicml-internal-integration-testing'
          export SFTP_URI='sftp://mosaicml-integration-testing@s-c07c6cb0dd1441dbb.server.transfer.us-west-2.amazonaws.com/mosaicml-internal-integration-testing'
          python3 -m pytest
