name: Pytest-CPU
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  pytest:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - python_version: '3.8'
            container: mosaicml/pytorch:1.11.0_cpu-python3.8-ubuntu20.04
            markers: 'not daily and not vision and not gpu'
          - python_version: '3.9'
            container: mosaicml/pytorch:1.12.1_cpu-python3.9-ubuntu20.04
            markers: 'not daily and not vision and not gpu'
          - python_version: '3.9'
            container: mosaicml/pytorch_vision:1.12.1_cpu-python3.9-ubuntu20.04
            markers: 'not daily and vision and not gpu'
          - python_version: '3.10'
            container: mosaicml/pytorch:1.13.0_cpu-python3.10-ubuntu20.04
            markers: 'not daily and not vision and not gpu'
    container: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          set -ex
          export PATH=/composer-python:$PATH
          python -m pip install --upgrade pip wheel
          python -m pip install -e .[all]
      - name: Run Tests
        id: tests
        run: |
          set -ex
          export PATH=/composer-python:$PATH
          # python -m pytest -v --durations=20 -m '${{ matrix.markers }}'
          make test PYTEST='pytest' EXTRA_ARGS="--codeblocks -v --durations=20 -m '${{ matrix.markers }}'"
          make test-dist PYTEST='pytest' WORLD_SIZE=2 EXTRA_ARGS="--codeblocks -v --durations=20 -m '${{ matrix.markers }}'"
